export const styles = {
  page: {
    background: "radial-gradient(circle at top left, rgba(21,87,149,0.25), transparent 30%), radial-gradient(circle at top right, rgba(24,180,108,0.14), transparent 24%), #07111f",
    minHeight: "100vh",
    color: "white",
    fontFamily: "'Segoe UI', Arial, sans-serif",
    position: "relative",
    overflow: "hidden",
  },
  backgroundGlowOne: {
    position: "absolute",
    inset: "70px auto auto -120px",
    width: 320,
    height: 320,
    background: "radial-gradient(circle, rgba(70,140,255,0.22), transparent 70%)",
    pointerEvents: "none",
  },
  backgroundGlowTwo: {
    position: "absolute",
    inset: "auto -80px 60px auto",
    width: 300,
    height: 300,
    background: "radial-gradient(circle, rgba(47,214,123,0.16), transparent 70%)",
    pointerEvents: "none",
  },
  topbar: {
    position: "relative",
    zIndex: 1,
    padding: "20px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(138,148,166,0.18)",
    flexWrap: "wrap",
    gap: 16,
    backdropFilter: "blur(14px)",
  },
  brandEyebrow: {
    color: "#7dd3fc",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    fontSize: 12,
    marginBottom: 6,
  },
  brandTitle: {
    margin: 0,
    fontSize: 28,
  },
  statusBadge: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "rgba(10,18,32,0.72)",
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  container: {
    position: "relative",
    zIndex: 1,
    padding: "34px 20px 52px",
    maxWidth: 1180,
    margin: "0 auto",
  },
  heroPanel: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 20,
    alignItems: "stretch",
  },
  heroCopy: {
    padding: 28,
    borderRadius: 28,
    background: "linear-gradient(180deg, rgba(16,25,43,0.9), rgba(10,16,29,0.85))",
    border: "1px solid rgba(125,211,252,0.14)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.24)",
  },
  heroKicker: {
    color: "#7dd3fc",
    fontWeight: 700,
    marginBottom: 12,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    fontSize: 12,
  },
  heroTitle: {
    fontSize: 48,
    lineHeight: 1,
    margin: "0 0 14px 0",
    maxWidth: 700,
  },
  heroSubtitle: {
    color: "#aab7cc",
    fontSize: 18,
    margin: 0,
    lineHeight: 1.7,
    maxWidth: 740,
  },
  heroBullets: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 20,
  },
  heroBullet: {
    padding: "10px 14px",
    borderRadius: 999,
    background: "rgba(14,22,39,0.9)",
    border: "1px solid rgba(125,211,252,0.18)",
    color: "#d5dcec",
    fontWeight: 600,
  },
  heroSideCard: {
    padding: 24,
    borderRadius: 28,
    background: "linear-gradient(180deg, rgba(9,17,30,0.96), rgba(7,14,25,0.92))",
    border: "1px solid rgba(47,214,123,0.16)",
    boxShadow: "0 18px 48px rgba(0,0,0,0.24)",
  },
  sideCardLabel: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    fontSize: 12,
    marginBottom: 10,
  },
  sideCardValue: {
    fontSize: 26,
    fontWeight: 800,
    marginBottom: 12,
  },
  sideCardText: {
    color: "#c5d0e0",
    lineHeight: 1.7,
    margin: "0 0 10px 0",
  },
  inlineCode: {
    display: "inline-block",
    fontSize: 12,
    padding: "4px 8px",
    borderRadius: 8,
    background: "rgba(255,255,255,0.08)",
    color: "#f4f7ff",
    wordBreak: "break-all",
  },
  searchPanel: {
    marginTop: 22,
    padding: 22,
    borderRadius: 24,
    background: "rgba(10,18,32,0.84)",
    border: "1px solid rgba(138,148,166,0.14)",
  },
  searchHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  searchTitle: {
    fontSize: 22,
    fontWeight: 800,
    marginBottom: 4,
  },
  searchHint: {
    color: "#8a94a6",
  },
  lastUpdated: {
    color: "#8a94a6",
    fontSize: 13,
  },
  searchRow: {
    display: "flex",
    gap: 12,
    marginTop: 18,
    flexWrap: "wrap",
  },
  quickRow: {
    display: "flex",
    gap: 10,
    marginTop: 14,
    flexWrap: "wrap",
  },
  historyWrap: {
    marginTop: 18,
  },
  historyHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  historyLabel: {
    color: "#8a94a6",
    fontSize: 13,
  },
  ghostButton: {
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "transparent",
    color: "#8a94a6",
    cursor: "pointer",
  },
  historyRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  historyButton: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    cursor: "pointer",
  },
  favoriteButton: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "rgba(47,214,123,0.1)",
    border: "1px solid rgba(47,214,123,0.24)",
    color: "#dff9ea",
    cursor: "pointer",
  },
  input: {
    flex: 1,
    minWidth: 260,
    padding: 16,
    borderRadius: 14,
    border: "1px solid rgba(125,211,252,0.22)",
    background: "#0e1728",
    color: "white",
    fontSize: 16,
  },
  primaryButton: {
    padding: "15px 22px",
    borderRadius: 14,
    background: "linear-gradient(135deg, #46b8ff, #2fd67b)",
    color: "#05111e",
    fontWeight: 800,
    border: 0,
    cursor: "pointer",
    minWidth: 130,
  },
  secondaryButton: {
    marginTop: 14,
    padding: "11px 14px",
    borderRadius: 12,
    background: "rgba(255,255,255,0.08)",
    color: "#f4f7ff",
    border: "1px solid rgba(255,255,255,0.14)",
    cursor: "pointer",
  },
  quickButton: {
    padding: "9px 13px",
    borderRadius: 999,
    background: "#101a2d",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    cursor: "pointer",
  },
  tabRow: {
    display: "flex",
    gap: 10,
    marginTop: 18,
    flexWrap: "wrap",
  },
  summaryStrip: {
    display: "flex",
    gap: 10,
    marginTop: 16,
    flexWrap: "wrap",
  },
  metaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 14,
    marginTop: 18,
  },
  metaGridCompact: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 14,
    marginTop: 18,
  },
  metaCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.14)",
    borderRadius: 18,
    padding: 16,
  },
  metaLabel: {
    color: "#8a94a6",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: 8,
  },
  metaValue: {
    color: "#f4f7ff",
    fontWeight: 800,
    marginBottom: 8,
  },
  metaText: {
    color: "#c5d0e0",
    lineHeight: 1.7,
  },
  metaSubtext: {
    color: "#8a94a6",
    marginTop: 10,
    fontSize: 13,
  },
  providerList: {
    marginTop: 10,
    display: "grid",
    gap: 8,
  },
  providerNote: {
    color: "#aab7cc",
    lineHeight: 1.5,
    fontSize: 14,
  },
  providerHealthGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))",
    gap: 12,
  },
  providerHealthCard: {
    background: "#08111f",
    padding: 14,
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
  },
  providerHealthError: {
    marginTop: 10,
    color: "#f1d5d5",
    lineHeight: 1.6,
    fontSize: 13,
  },
  providerHealthOk: {
    marginTop: 10,
    color: "#a6f3c2",
    lineHeight: 1.6,
    fontSize: 13,
  },
  explainerRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
    marginTop: 18,
  },
  explainerCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.14)",
    borderRadius: 18,
    padding: 16,
  },
  explainerTitle: {
    fontWeight: 800,
    marginBottom: 6,
    color: "#f4f7ff",
  },
  explainerText: {
    color: "#aab7cc",
    lineHeight: 1.7,
  },
  tabButton: {
    padding: "10px 14px",
    borderRadius: 999,
    background: "#0f172a",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    cursor: "pointer",
    fontWeight: 700,
  },
  tabButtonActive: {
    background: "linear-gradient(135deg, rgba(70,184,255,0.16), rgba(47,214,123,0.16))",
    border: "1px solid rgba(70,184,255,0.38)",
    color: "#f8fafc",
  },
  loadingCard: {
    marginTop: 22,
    padding: 18,
    borderRadius: 22,
    background: "rgba(70,184,255,0.08)",
    border: "1px solid rgba(70,184,255,0.18)",
    display: "flex",
    gap: 16,
    alignItems: "center",
  },
  loadingPulse: {
    width: 18,
    height: 18,
    borderRadius: 999,
    background: "#46b8ff",
    boxShadow: "0 0 0 10px rgba(70,184,255,0.16)",
  },
  loadingTitle: {
    fontWeight: 800,
    marginBottom: 4,
  },
  loadingText: {
    color: "#c5d0e0",
  },
  skeletonGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 12,
    marginTop: 16,
  },
  skeletonCard: {
    minHeight: 110,
    borderRadius: 18,
    background: "linear-gradient(90deg, rgba(255,255,255,0.04), rgba(255,255,255,0.08), rgba(255,255,255,0.04))",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  errorBox: {
    marginTop: 22,
    padding: 18,
    borderRadius: 22,
    background: "rgba(255,107,107,0.1)",
    border: "1px solid rgba(255,107,107,0.24)",
  },
  errorTitle: {
    fontWeight: 800,
    marginBottom: 6,
    color: "#ffb6b6",
  },
  errorText: {
    color: "#f1d5d5",
    lineHeight: 1.7,
  },
  noticeBox: {
    marginTop: 22,
    padding: 18,
    borderRadius: 22,
    background: "rgba(255,176,32,0.1)",
    border: "1px solid rgba(255,176,32,0.24)",
  },
  noticeTitle: {
    fontWeight: 800,
    marginBottom: 6,
    color: "#ffd789",
  },
  noticeText: {
    color: "#f3e4bf",
    lineHeight: 1.7,
  },
  pickerPanel: {
    marginTop: 22,
    padding: 18,
    borderRadius: 22,
    background: "rgba(125,211,252,0.08)",
    border: "1px solid rgba(125,211,252,0.22)",
  },
  pickerTitle: {
    fontWeight: 800,
    marginBottom: 6,
    color: "#d8f3ff",
  },
  pickerText: {
    color: "#c9d8ec",
    lineHeight: 1.7,
  },
  pickerGrid: {
    display: "grid",
    gap: 12,
    marginTop: 16,
  },
  pickerCard: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: 14,
    alignItems: "center",
    padding: 14,
    borderRadius: 16,
    background: "rgba(8,17,31,0.94)",
    border: "1px solid rgba(138,148,166,0.14)",
  },
  pickerLogo: {
    width: 40,
    height: 40,
    borderRadius: 999,
    objectFit: "cover",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(138,148,166,0.14)",
  },
  pickerLogoFallback: {
    width: 40,
    height: 40,
    borderRadius: 999,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(138,148,166,0.14)",
    color: "#d8f3ff",
    fontWeight: 800,
  },
  pickerName: {
    fontWeight: 800,
    color: "#f8fbff",
    marginBottom: 4,
  },
  pickerMeta: {
    color: "#8a94a6",
    fontSize: 13,
    lineHeight: 1.6,
  },
  pickerChipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 8,
  },
  pickerChip: {
    padding: "6px 10px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.16)",
    color: "#d5dcec",
    fontSize: 12,
    fontWeight: 700,
  },
  pickerActionCol: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "flex-end",
  },
  watchlistGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
  },
  watchlistCard: {
    padding: 16,
    borderRadius: 16,
    border: "1px solid rgba(138,148,166,0.14)",
    background: "#08111f",
  },
  watchlistHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  watchlistIdentityRow: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  watchlistSubtitle: {
    color: "#8a94a6",
    fontSize: 13,
    lineHeight: 1.6,
  },
  watchlistActionRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 14,
  },
  watchlistToolbar: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  watchlistFilterRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 14,
  },
  watchlistFilterButtonActive: {
    background: "rgba(70,184,255,0.14)",
    border: "1px solid rgba(70,184,255,0.34)",
    color: "#f8fbff",
  },
  watchlistSelect: {
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "#0f172a",
    color: "#f4f7ff",
    minWidth: 180,
  },
  watchlistCountText: {
    color: "#8a94a6",
    fontSize: 12,
    marginLeft: "auto",
  },
  watchlistBatchSummary: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 14,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  watchlistBatchSummaryTitle: {
    color: "#f4f7ff",
    fontWeight: 800,
    marginBottom: 8,
  },
  watchlistBatchSummaryText: {
    color: "#c5d0e0",
    lineHeight: 1.6,
    marginTop: 10,
    fontSize: 14,
  },
  watchlistSummaryText: {
    color: "#d5dcec",
    lineHeight: 1.7,
    marginTop: 12,
  },
  watchlistStatusRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 10,
  },
  watchlistStatusChip: {
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "#0f172a",
    fontSize: 12,
    fontWeight: 700,
  },
  watchlistStatusDetail: {
    color: "#8a94a6",
    fontSize: 12,
    lineHeight: 1.5,
  },
  watchlistTimestampRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 6,
  },
  watchlistTimestampLabel: {
    color: "#8a94a6",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  watchlistTimestampValue: {
    color: "#d5dcec",
    fontSize: 12,
  },
  watchlistRefreshResultRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 6,
  },
  watchlistRefreshResultChip: {
    padding: "5px 10px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "#0f172a",
    fontSize: 12,
    fontWeight: 700,
  },
  watchlistRefreshResultDetail: {
    color: "#8a94a6",
    fontSize: 12,
    lineHeight: 1.5,
  },
  scoreContributorTopDriversWrap: {
    marginTop: 4,
  },
  scoreContributorTopDriversTitle: {
    color: "#f4f7ff",
    fontWeight: 700,
    marginBottom: 10,
  },
  scoreContributorChipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  scoreContributorChip: {
    padding: "7px 10px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    fontSize: 12,
    fontWeight: 700,
  },
  scoreContributorGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 14,
    marginTop: 16,
  },
  scoreContributorGroup: {
    background: "#08111f",
    padding: 14,
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
  },
  scoreContributorGroupTitle: {
    fontWeight: 800,
    marginBottom: 10,
  },
  scoreContributorList: {
    display: "grid",
    gap: 10,
  },
  scoreContributorItem: {
    padding: 12,
    borderRadius: 12,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  scoreContributorItemHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 6,
  },
  scoreContributorArea: {
    color: "#f4f7ff",
    fontWeight: 700,
    fontSize: 13,
  },
  scoreContributorStrength: {
    padding: "4px 8px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    fontSize: 11,
    fontWeight: 700,
    background: "rgba(255,255,255,0.02)",
  },
  scoreContributorSummary: {
    color: "#c5d0e0",
    lineHeight: 1.6,
    fontSize: 14,
  },
  scoreContributorEmpty: {
    color: "#8a94a6",
    lineHeight: 1.6,
    fontSize: 13,
  },
  emptyState: {
    marginTop: 22,
    padding: 18,
    borderRadius: 22,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.14)",
  },
  emptyTitle: {
    fontWeight: 800,
    marginBottom: 6,
  },
  emptyText: {
    color: "#8a94a6",
  },
  resultCard: {
    background: "rgba(10,18,32,0.88)",
    padding: 24,
    borderRadius: 24,
    marginTop: 24,
    border: "1px solid rgba(138,148,166,0.14)",
  },
  resultHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  resultActions: {
    display: "flex",
    gap: 10,
    marginTop: 16,
    flexWrap: "wrap",
    alignItems: "center",
  },
  actionButton: {
    padding: "10px 14px",
    borderRadius: 12,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "rgba(255,255,255,0.04)",
    color: "#f4f7ff",
    cursor: "pointer",
  },
  copyMessage: {
    color: "#8a94a6",
    fontSize: 13,
  },
  analysisQualityNote: {
    marginTop: 0,
    padding: 16,
    borderRadius: 18,
  },
  analysisQualityTitle: {
    fontWeight: 800,
    marginBottom: 6,
  },
  analysisQualityText: {
    lineHeight: 1.7,
  },
  sectionHint: {
    marginTop: 10,
    marginBottom: 12,
    padding: "10px 12px",
    borderRadius: 12,
    lineHeight: 1.6,
    fontSize: 14,
  },
  freshnessWrap: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 4,
    marginBottom: 10,
  },
  freshnessBadge: {
    padding: "5px 10px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "rgba(255,255,255,0.02)",
    fontSize: 12,
    fontWeight: 700,
  },
  freshnessDetail: {
    color: "#8a94a6",
    fontSize: 12,
  },
  panelStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 4,
    marginBottom: 10,
  },
  panelStatusHint: {
    flex: 1,
    minWidth: 220,
    padding: "8px 10px",
    borderRadius: 12,
    lineHeight: 1.5,
    fontSize: 13,
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 12,
    marginTop: 20,
  },
  inlineGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 12,
    marginTop: 14,
  },
  box: {
    background: "#08111f",
    padding: 14,
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
  },
  boxLabel: {
    fontSize: 12,
    color: "#8a94a6",
    marginBottom: 6,
  },
  boxValue: {
    fontWeight: 700,
    color: "#f4f7ff",
  },
  boxTone: {
    marginTop: 6,
    color: "#9bd7ff",
    fontSize: 12,
  },
  sectionRow: {
    marginTop: 12,
    padding: 12,
    background: "#08111f",
    borderRadius: 12,
    border: "1px solid rgba(138,148,166,0.12)",
  },
  sectionRowLabel: {
    fontSize: 12,
    color: "#8a94a6",
    marginBottom: 6,
  },
  sectionRowValue: {
    color: "#e2e8f0",
    lineHeight: 1.7,
  },
  cardWide: {
    background: "rgba(10,18,32,0.88)",
    padding: 20,
    borderRadius: 20,
    border: "1px solid rgba(138,148,166,0.14)",
    marginTop: 16,
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    marginBottom: 12,
  },
  advancedGrid: {
    marginTop: 20,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 16,
  },
  advancedGridSingle: {
    marginTop: 4,
  },
  timelineStack: {
    display: "grid",
    gap: 14,
  },
  timelineEntry: {
    padding: 16,
    borderRadius: 16,
    border: "1px solid rgba(138,148,166,0.14)",
    background: "#08111f",
  },
  timelineEntryActive: {
    borderColor: "rgba(70,184,255,0.36)",
    boxShadow: "0 0 0 1px rgba(70,184,255,0.12) inset",
  },
  timelineEntryHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  timelineTitleRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  timelineMeta: {
    color: "#8a94a6",
    fontSize: 13,
    marginTop: 6,
    lineHeight: 1.5,
  },
  timelineSummary: {
    color: "#d5dcec",
    lineHeight: 1.7,
    marginTop: 12,
  },
  timelineChipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 12,
  },
  timelineSubsectionTitle: {
    marginTop: 14,
    color: "#f4f7ff",
    fontWeight: 700,
  },
  timelineActionRow: {
    marginTop: 16,
    display: "flex",
    justifyContent: "flex-start",
  },
  timelineEmptyText: {
    color: "#8a94a6",
    lineHeight: 1.7,
  },
  inlineErrorBox: {
    marginTop: 12,
    padding: 14,
    borderRadius: 16,
    background: "rgba(255,107,107,0.08)",
    border: "1px solid rgba(255,107,107,0.2)",
  },
  inlineErrorTitle: {
    color: "#ffb6b6",
    fontWeight: 800,
    marginBottom: 6,
  },
  inlineErrorText: {
    color: "#f1d5d5",
    lineHeight: 1.6,
  },
  compareToolbar: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 12,
    marginBottom: 12,
  },
  compareMetaBlock: {
    background: "#08111f",
    padding: 14,
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
  },
  compareSummaryHeader: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  contextGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
    marginTop: 16,
  },
  contextCard: {
    background: "#08111f",
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
    padding: 14,
  },
  contextLead: {
    color: "#d5dcec",
    lineHeight: 1.7,
  },
  contextMuted: {
    color: "#8a94a6",
    lineHeight: 1.6,
    marginTop: 10,
    fontSize: 13,
  },
  contextDetails: {
    marginTop: 14,
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
    background: "rgba(255,255,255,0.02)",
    overflow: "hidden",
  },
  contextSummary: {
    cursor: "pointer",
    padding: "14px 16px",
    color: "#f4f7ff",
    fontWeight: 800,
    listStyle: "none",
  },
  contextDetailsBody: {
    padding: "0 16px 16px",
  },
  snapshotDetailWrap: {
    marginTop: 18,
  },
  snapshotDetailHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 14,
    alignItems: "flex-start",
    flexWrap: "wrap",
    marginTop: 8,
    marginBottom: 8,
  },
  snapshotDetailEyebrow: {
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 12,
    marginBottom: 8,
  },
  snapshotDetailTitle: {
    margin: "0 0 8px 0",
    color: "#f4f7ff",
  },
  snapshotDetailText: {
    color: "#aab7cc",
    lineHeight: 1.7,
  },
  select: {
    width: "100%",
    marginTop: 6,
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid rgba(138,148,166,0.2)",
    background: "#0f172a",
    color: "#f4f7ff",
  },
  scoreRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: "10px 0",
    borderBottom: "1px solid rgba(138,148,166,0.12)",
  },
  scorePill: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "#0f172a",
    fontWeight: 700,
  },
  riskLevelRow: {
    display: "flex",
    gap: 10,
    marginTop: 14,
    flexWrap: "wrap",
  },
  riskChip: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "#0f172a",
    fontWeight: 700,
  },
  eventMeta: {
    display: "flex",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap",
  },
  progressOuter: {
    height: 8,
    background: "#0b1220",
    borderRadius: 999,
    overflow: "hidden",
    marginBottom: 14,
    border: "1px solid rgba(138,148,166,0.12)",
  },
  progressInner: {
    height: "100%",
    borderRadius: 999,
  },
  disclaimer: {
    marginTop: 28,
    background: "rgba(249,217,118,0.08)",
    border: "1px solid rgba(249,217,118,0.2)",
    borderRadius: 20,
    padding: 20,
  },
  heroNav: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  heroButtonRow: {
    display: "flex",
    gap: 12,
    marginTop: 22,
    flexWrap: "wrap",
  },
  trustStrip: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 18,
    marginBottom: 18,
  },
  trustStripItem: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(138,148,166,0.14)",
    color: "#d5dcec",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  decisionHeroWrap: {
    position: "sticky",
    top: 12,
    zIndex: 2,
  },
  decisionHeroTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 18,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  decisionHeroPrimaryColumn: {
    flex: "1 1 360px",
  },
  decisionHeroMetaColumn: {
    display: "flex",
    justifyContent: "flex-end",
    flex: "0 1 320px",
  },
  decisionHeroEyebrow: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 12,
    marginBottom: 8,
  },
  decisionHeroOutcome: {
    fontSize: 42,
    fontWeight: 900,
    lineHeight: 1,
  },
  decisionHeroInvestabilityBadge: {
    marginTop: 10,
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.18)",
  },
  decisionHeroInvestabilityLabel: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 11,
    fontWeight: 700,
  },
  decisionHeroInvestabilityValue: {
    color: "#f4f7ff",
    fontWeight: 800,
  },
  decisionHeroScoreRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  decisionHeroScoreBlock: {
    minWidth: 180,
    padding: 14,
    borderRadius: 14,
    background: "#08111f",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  decisionHeroMetricLabel: {
    color: "#8a94a6",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: 6,
  },
  decisionHeroMetricValue: {
    color: "#f4f7ff",
    fontSize: 28,
    fontWeight: 800,
  },
  decisionHeroMetricValueSmall: {
    color: "#f4f7ff",
    fontSize: 22,
    fontWeight: 800,
  },
  decisionHeroBadgeRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 16,
  },
  institutionalBadge: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid rgba(138,148,166,0.18)",
    background: "rgba(255,255,255,0.03)",
    color: "#d5dcec",
    fontSize: 12,
    fontWeight: 700,
  },
  contradictionBanner: {
    marginTop: 18,
    padding: 14,
    borderRadius: 14,
    background: "rgba(255,107,107,0.08)",
    border: "1px solid rgba(255,107,107,0.22)",
  },
  contradictionTitle: {
    color: "#ffb6b6",
    fontWeight: 800,
    marginBottom: 6,
  },
  contradictionText: {
    color: "#f1d5d5",
    lineHeight: 1.6,
  },
  evidenceConstraintBanner: {
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    background: "rgba(125,211,252,0.08)",
    border: "1px solid rgba(125,211,252,0.18)",
  },
  evidenceConstraintTitle: {
    color: "#b7ecff",
    fontWeight: 800,
    marginBottom: 6,
  },
  evidenceConstraintText: {
    color: "#d8f3ff",
    lineHeight: 1.6,
  },
  decisionDominanceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 14,
    marginTop: 16,
  },
  decisionDominanceBlock: {
    padding: 16,
    borderRadius: 16,
    background: "#08111f",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  decisionDominanceLabel: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 8,
  },
  decisionDominanceValue: {
    color: "#f4f7ff",
    fontSize: 18,
    fontWeight: 700,
    lineHeight: 1.55,
  },
  decisionDominanceMutedValue: {
    color: "#c5d0e0",
    fontSize: 15,
    lineHeight: 1.65,
  },
  decisionHeroSecondaryBand: {
    marginTop: 16,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 12,
    alignItems: "stretch",
  },
  decisionHeroSecondaryMetric: {
    padding: 12,
    borderRadius: 14,
    background: "rgba(255,255,255,0.02)",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  decisionHeroSecondaryLabel: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
  },
  decisionHeroSecondaryValue: {
    color: "#d5dcec",
    fontSize: 18,
    fontWeight: 800,
  },
  decisionHeroSecondaryNarrative: {
    padding: 12,
    borderRadius: 14,
    background: "rgba(255,255,255,0.02)",
    border: "1px solid rgba(138,148,166,0.12)",
    color: "#c5d0e0",
    lineHeight: 1.6,
  },
  decisionDriverPanel: {
    marginTop: 16,
  },
  decisionDriverTitle: {
    color: "#f4f7ff",
    fontWeight: 800,
    marginBottom: 8,
  },
  decisionDriverChip: {
    padding: "9px 12px",
    borderRadius: 12,
    background: "#08111f",
    border: "1px solid rgba(138,148,166,0.12)",
    color: "#e2e8f0",
    fontSize: 13,
    lineHeight: 1.4,
  },
  terminalNav: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 18,
    marginBottom: 4,
  },
  terminalNavHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 18,
  },
  terminalNavTitle: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 12,
    fontWeight: 700,
  },
  terminalNavHint: {
    color: "#aab7cc",
    fontSize: 13,
  },
  decisionNavigatorWrap: {
    marginTop: 18,
  },
  decisionNavigatorTitle: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 10,
  },
  decisionNavigatorRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  decisionNavigatorButton: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "#0f172a",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
  },
  decisionNavigatorButtonActive: {
    background: "rgba(70,184,255,0.14)",
    border: "1px solid rgba(70,184,255,0.34)",
    color: "#f8fbff",
  },
  flagStripWrap: {
    marginTop: 16,
    padding: 16,
    borderRadius: 16,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(138,148,166,0.12)",
  },
  flagStripTitle: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 12,
    marginBottom: 10,
  },
  flagStripRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  flagStripChip: {
    padding: "8px 11px",
    borderRadius: 999,
    background: "#0f172a",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    fontSize: 12,
    fontWeight: 700,
  },
  decisionMatrixGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  decisionMatrixCell: {
    background: "#08111f",
    borderRadius: 14,
    border: "1px solid rgba(138,148,166,0.12)",
    padding: 14,
  },
  decisionMatrixTitle: {
    color: "#f4f7ff",
    fontWeight: 800,
    marginBottom: 8,
  },
  selectorPanel: {
    marginTop: 22,
    padding: 18,
    borderRadius: 22,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.14)",
  },
  selectorHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  selectorEyebrow: {
    color: "#8a94a6",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 12,
    marginBottom: 8,
  },
  selectorTitle: {
    color: "#f4f7ff",
    fontSize: 22,
    fontWeight: 800,
    marginBottom: 6,
  },
  selectorText: {
    color: "#c5d0e0",
    lineHeight: 1.7,
  },
  selectorFilterRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 16,
    marginBottom: 16,
  },
  selectorFilterButton: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "#101a2d",
    border: "1px solid rgba(138,148,166,0.18)",
    color: "#d5dcec",
    cursor: "pointer",
  },
  selectorFilterButtonActive: {
    background: "rgba(70,184,255,0.14)",
    border: "1px solid rgba(70,184,255,0.34)",
    color: "#f8fbff",
  },
  selectorGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 14,
  },
  selectorCard: {
    padding: 16,
    borderRadius: 16,
    border: "1px solid rgba(138,148,166,0.14)",
    background: "#08111f",
  },
  selectorIdentity: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  selectorLogo: {
    width: 42,
    height: 42,
    borderRadius: 999,
    objectFit: "cover",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(138,148,166,0.14)",
  },
  selectorLogoFallback: {
    width: 42,
    height: 42,
    borderRadius: 999,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(138,148,166,0.14)",
    color: "#d8f3ff",
    fontWeight: 800,
  },
  selectorName: {
    fontWeight: 800,
    color: "#f8fbff",
    marginBottom: 4,
  },
  selectorMeta: {
    color: "#8a94a6",
    fontSize: 13,
    lineHeight: 1.6,
    marginTop: 10,
  },
  selectorChipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 12,
    marginBottom: 12,
  },
  selectorChip: {
    padding: "6px 10px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(138,148,166,0.16)",
    color: "#d5dcec",
    fontSize: 12,
    fontWeight: 700,
  },
  auditSection: {
    marginTop: 14,
    borderRadius: 16,
    border: "1px solid rgba(138,148,166,0.12)",
    background: "rgba(255,255,255,0.02)",
    overflow: "hidden",
  },
  auditSummary: {
    display: "flex",
    justifyContent: "space-between",
    gap: 10,
    alignItems: "center",
    cursor: "pointer",
    padding: "16px 18px",
    color: "#f4f7ff",
    fontWeight: 800,
    listStyle: "none",
  },
  auditSummaryMeta: {
    color: "#8a94a6",
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  auditBody: {
    padding: "0 18px 18px",
  },
  methodologyText: {
    color: "#aab7cc",
    lineHeight: 1.7,
    marginTop: 14,
  },
};




